CREATE TABLE Player 
(
	player_id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(20)UNIQUE NOT NULL,
	email VARCHAR(50)UNIQUE NOT NULL,
	level INT DEFAULT 1,
	current_balance INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
