CREATE TABLE Transactions(
	transactionId INT IDENTITY(1,1) PRIMARY KEY,
	player_id INT FOREIGN KEY REFERENCES Player(player_id),
	item_id INT FOREIGN KEY REFERENCES ITEMS(item_id),
	amount INT DEFAULT 0 NOT NULL,
	[timestamp] DATETIME2 DEFAULT GETDATE() NOT NULL
);